# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('screenshot', models.ImageField(null=True, upload_to='images/')),
                ('description', models.TextField(null=True)),
                ('link', tinymce.models.HTMLField()),
            ],
        ),
    ]
