# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0003_auto_20181012_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(),
        ),
    ]
